// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuizZoBFdCed_8SubCpybTrsypBN_u8No',
    appId: '1:120185473230:web:4341505168d9b64bb2e89f',
    messagingSenderId: '120185473230',
    projectId: 'we-healthy-project',
    authDomain: 'we-healthy-project.firebaseapp.com',
    storageBucket: 'we-healthy-project.appspot.com',
    measurementId: 'G-J9DPSP8FCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0VfcMzTTQ3b_aQihtUXUxZ2sie_D-icI',
    appId: '1:120185473230:android:e40841d570c6c40db2e89f',
    messagingSenderId: '120185473230',
    projectId: 'we-healthy-project',
    storageBucket: 'we-healthy-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyzFq50KOk7OREj23yw4IsU6Y8GCr7OfA',
    appId: '1:120185473230:ios:fa80d13e765e5f57b2e89f',
    messagingSenderId: '120185473230',
    projectId: 'we-healthy-project',
    storageBucket: 'we-healthy-project.appspot.com',
    iosBundleId: 'com.example.weHealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyzFq50KOk7OREj23yw4IsU6Y8GCr7OfA',
    appId: '1:120185473230:ios:471f49e23ef1b9cfb2e89f',
    messagingSenderId: '120185473230',
    projectId: 'we-healthy-project',
    storageBucket: 'we-healthy-project.appspot.com',
    iosBundleId: 'com.example.weHealthy.RunnerTests',
  );
}
